version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
    networks:
      - aspnet

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    depends_on:
      - db
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar
    networks:
      - aspnet

  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - aspnet
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 23
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    ports:
      - 443:443
      - 80:80
      - 23:22
    networks:
      - aspnet

networks:
  aspnet:
